### ISSUE TITLE
v1 functionality roadmap

### ISSUE THREAD

**Issue by wyrmroot** [wyrmroot/qs3#1]
## Bucket browser
- [ ] Show list of all buckets the current account has access to
- [ ] Select a bucket from the list
    - [ ] By number
    - [ ] By tab completion
    - [ ] By arrow keys
- [ ] `Tab` Show stats on selected bucket
- [ ] Enter to list items in bucket

## Object lister
- [x] `f` page forward
- [x] `b` page down
- [x] Show items alphabetically
- [ ] Toggle detail/column mode
- [x] Click to select
- [ ] `/` to filter
    - [ ] First match shown in dark text following input, `Tab` completes it
- [ ] `#`, `Enter` Navigate to numbered item
- [ ] Allow direct jump to other paths, including back/forward nav independent of parent/child nav
- [x] `ctrl`+`r` Force refresh

## File pager
- [x] `f` page forward
- [x] `b` page down
- [x] inflate .gz files by magic byte signature
- [ ] show binary files as base64
- [ ] show encoding in status bar
- [x] color by delimiter
    - [x] `,` configure delimiter
    - [ ] user can input new delimiter
- [x] `ctrl`+`w` Toggle line wrap
- [x] `ctrl`+`n` toggle line numbers
- [x] `ESC`, `ctrl`+`d`: Close pager, return to lister
- [x] `ctrl`+`c`: Quit application
- [x] `ctrl`+`r` Force refresh
